version: "3.1"

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: safepassword
      MYSQL_PASSWORD: secret
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      